---
title: "My Dazzling Report"
author: "Lindsey Dietz, PhD"
date: "2021-03-18"
output: 
  html_document:
    code_folding: hide
params:
  month: 03
  year: 2021

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is my monthly report for ``r params$date``.

# {.tabset .tabset-pills}

## The Info

Using tabs: https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html

https://rstudio.com/resources/rstudioconf-2020/rmarkdown-driven-development/

Packages I'm going to use

```{r, warning=FALSE, message=FALSE, class.source = 'fold-show'}
#The report
library(rmarkdown)

#Tables
library(DT)
library(reactable)

#Plots
library(ggplot2)
library(plotly)

```


```{r}
library(dplyr)
library(fredr)

df1 <- fredr(
  series_id = "UNRATE",
  observation_start = as.Date("2002-01-01"),
  observation_end = as.Date(paste(params$year, params$month, '01', sep = "-"))
) %>% mutate(series_id = " Total")

df2 <- fredr(
  series_id = "LNS14000006",
  observation_start = as.Date("2002-01-01"),
  observation_end = as.Date(paste(params$year, params$month, '01', sep = "-"))
) %>% mutate(series_id = "Black/African American")
  

df3 <- fredr(
  series_id = "LNS14000003",
  observation_start = as.Date("2002-01-01"),
  observation_end = as.Date(paste(params$year, params$month, '01', sep = "-"))
) %>% mutate(series_id = "White")

df4 <- fredr(
  series_id = "LNS14000009",
  observation_start = as.Date("2002-01-01"),
  observation_end = as.Date(paste(params$year, params$month, '01', sep = "-"))
) %>% mutate(series_id = "Hispanic/Latino")


df <- rbind(df1, df2, df3, df4) %>%
  rename(Category = series_id,
         Date = date,
         UR = value) %>%
  select(-realtime_start, -realtime_end) %>%
  mutate(recession = ifelse(Date >= '2020-02-01' | (Date >= '2007-12-01' & Date < '2009-07-01') | (Date >= '2001-03-01' & Date < '2001-12-01'), TRUE, FALSE),
         quarter_start = ifelse(substr(Date, 6, 7) %in% c('01','04','07','10'), TRUE, FALSE))

```

## Interactive Table with DT

```{r cars, echo=FALSE}
DT::datatable(df, filter = 'top', extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel')))
```

## Interactive Table with reactable

```{r data, echo=FALSE}

orange_pal <- function(x) rgb(colorRamp(c('#FFFFFF', "#ffb54d", "#B22222"))(x), maxColorValue = 255)

reactable::reactable(df, filterable = TRUE, groupBy = "Category", 
  columns = list(
    UR = colDef(
      style = function(UR) {
        normalized <- (UR - min(df$UR)) / (max(df$UR) - min(df$UR))
        color <- orange_pal(normalized)
        list(background = color)
      }
    )
  )
)

```


## Interactive Plot

You can also embed plots, for example:

```{r ur, echo=FALSE, message=FALSE, warning=FALSE, fig.width=10}
myplot <- ggplot(df, aes(x = Date, y = UR, color = Category)) + 
  geom_line() +
  theme_bw() + ylab("Unemployment Rate")

ggplotly(myplot)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Dropdown in a tab
