---
title: "Dazzling HTML Reports"
author: "Lindsey Dietz, PhD"
date: "R-Ladies Twin Cities (March 18, 2021)"
output:
  revealjs::revealjs_presentation:
    theme: black
    highlight: monochrome
    transition: fade

---

## Goal of this talk

Introduce tools that help you tell a data story in a professional, sustainable, and beautiful way

## Older process

- Do analysis in one tool (R)
- Make tables and charts in another tool (Excel)
- Paste everything into a text editor (Word)
- Turn it into a final product (PDF)

It works, but doesn't set you up for next time.

## Building an R ecosystem for everything

- R project is the forest
- R markdown is the tree
- Tables and plots are the animals in the tree
    + Table building using `DT` or `reactable` (or others)
    + Plotting using `ggplot2` or `plotly`

## R Project

R projects define your working directories. This helps keeps paths relative rather than fixed. This makes the work portable and lets you introduce folders to keep things tidy. 

## R Markdown

Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

- YAML Header
- Code chunks
- Markdown/LaTeX

## Tables

There are many table packages. I chose a couple that are good for HTML reports

- `DT` - lighter weight starting point
- `reactable` - more advanced customization

## Plots

`ggplot2` works great on it's own. It can be enhanced by adding `plotly`.


<style type="text/css">
  .reveal p {
    text-align: left;
  }
  .reveal ul {
    display: block;
  }
  .reveal ol {
    display: block;
  }  
</style>